name: Documentation Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install markdown-link-check
      run: |
        npm install -g markdown-link-check
    
    - name: Check for broken links in Markdown files
      run: |
        echo "Checking for broken links in documentation..."
        find docs/ -name "*.md" -type f -exec markdown-link-check {} \;
        markdown-link-check README.md
      continue-on-error: true
    
    - name: Validate documentation structure
      run: |
        echo "Validating documentation structure..."
        # Check if required documentation files exist
        required_files=(
          "docs/index.md"
          "docs/user_guide/index.md"
          "docs/api_reference/index.md"
          "docs/algorithm_reference/index.md"
          "docs/examples/index.md"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "ERROR: Required documentation file $file is missing!"
            exit 1
          else
            echo "$file exists ✓"
          fi
        done
        
        echo "Documentation structure validation passed ✓"