name: Publish Python Package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 0.1.0)'
        required: true
        default: '0.1.0'
      pypi_environment:
        description: 'PyPI environment (test or production)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'false'
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Update version if workflow dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        poetry version ${{ github.event.inputs.version }}
        echo "Updated version to ${{ github.event.inputs.version }}"
    
    - name: Build package
      run: |
        poetry build
    
    - name: Publish package to TestPyPI
      if: github.event.inputs.pypi_environment == 'test' || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    
    - name: Publish package to PyPI
      if: github.event.inputs.pypi_environment == 'production'
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
    
    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        name: "v${{ github.event.inputs.version }}"
        tag_name: "v${{ github.event.inputs.version }}"
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}